function t280_showMenu(recid){var el=$("#rec"+recid);el.find('.t280__burger, .t280__menu__bg, .t280__menu__item:not(".tooltipstered"):not(".t280__menu__item_submenu")').click(function(){if($(this).is(".t280__menu__item.tooltipstered, .t794__tm-link")){return}
$('body').toggleClass('t280_opened');el.find('.t280').toggleClass('t280__main_opened');var isChrome=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor);if(window.location.hash&&isChrome){setTimeout(function(){var hash=window.location.hash;window.location.hash="";window.location.hash=hash},50)}
t280_changeSize(recid)});$('.t280').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t280_opened');el.find('.t280').removeClass('t280__main_opened')});if(el.find('.t-menusub__link-item')){el.find('.t-menusub__link-item').on('click',function(){$('body').removeClass('t280_opened');el.find('.t280').removeClass('t280__main_opened')})}}
function t280_changeSize(recid){var el=$("#rec"+recid);var div=el.find(".t280__menu").height();var bottomheight=el.find(".t280__bottom").height();var headerheight=el.find(".t280__container").height();var wrapper=el.find(".t280__menu__wrapper");var win=$(window).height()-bottomheight-headerheight-160;if(div>win){wrapper.addClass('t280__menu_static')}
else{wrapper.removeClass('t280__menu_static')}}
function t280_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t280__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t280_appearMenu(){$('.t280').each(function(){var el=$(this);var appearoffset=el.attr('data-appearoffset');if(appearoffset!=''){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor(window.innerHeight*(parseInt(appearoffset)/100))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css('top','-50px');el.css('opacity','1');el.css('visibility','visible')}}else{el.stop();el.css('opacity','0');el.css('visibility','hidden')}}})}
function t280_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t280__menu a[href='"+url+"']").addClass("t-active");$(".t280__menu a[href='"+url+"/']").addClass("t-active");$(".t280__menu a[href='"+pathname+"']").addClass("t-active");$(".t280__menu a[href='/"+pathname+"']").addClass("t-active");$(".t280__menu a[href='"+pathname+"/']").addClass("t-active");$(".t280__menu a[href='/"+pathname+"/']").addClass("t-active")}
function t509_setHeight(recid){var t509__el=$("#rec"+recid);var t509__image=t509__el.find(".t509__blockimg");t509__image.each(function(){var t509__width=$(this).attr("data-image-width");var t509__height=$(this).attr("data-image-height");var t509__ratio=t509__height/t509__width;var t509__padding=t509__ratio*100;$(this).css("padding-bottom",t509__padding+"%")});if($(window).width()>960){var t509__textwr=t509__el.find(".t509__textwrapper");var t509__deskimg=t509__el.find(".t509__desktopimg");t509__textwr.each(function(){$(this).css("height",t509__deskimg.innerHeight())})}}
function t712_onSuccess(t712_form){var t712_inputsWrapper=t712_form.find('.t-form__inputsbox');var t712_inputsHeight=t712_inputsWrapper.height();var t712_inputsOffset=t712_inputsWrapper.offset().top;var t712_inputsBottom=t712_inputsHeight+t712_inputsOffset;var t712_targetOffset=t712_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t712_target=t712_targetOffset-200}else{var t712_target=t712_targetOffset-100}
if(t712_targetOffset>$(window).scrollTop()||($(document).height()-t712_inputsBottom)<($(window).height()-100)){t712_inputsWrapper.addClass('t712__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t712_target},400);setTimeout(function(){t712_inputsWrapper.addClass('t712__inputsbox_hidden')},400)}
var successurl=t712_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t712_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}